const apiConstants = {

    GET_MENU_LIST: "GET_MENU_LIST",
    GET_MENU_LIST_SUCCESS: "GET_MENU_LIST_SUCCESS",
    GET_MENU_LIST_FAIL: "GET_MENU_LIST_FAIL",

    GET_OFFERS_LIST: "GET_OFFERS_LIST",
    GET_OFFERS_LIST_SUCCESS: "GET_OFFERS_LIST_SUCCESS",
    GET_OFFERS_LIST_FAIL: "GET_OFFERS_LIST_FAIL",

    GET_BANNER_LIST: "GET_BANNER_LIST",
    GET_BANNER_LIST_SUCCESS: "GET_BANNER_LIST_SUCCESS",
    GET_BANNER_LIST_FAIL: "GET_BANNER_LIST_FAIL",

    GET_TODAY_DEALS_LIST: "GET_TODAY_DEALS_LIST",
    GET_TODAY_DEALS_LIST_SUCCESS: "GET_TODAY_DEALS_LIST_SUCCESS",
    GET_TODAY_DEALS_LIST_FAIL: "GET_TODAY_DEALS_LIST_FAIL",

    GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
    GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
    GET_PRODUCT_LIST_FAIL: "GET_PRODUCT_LIST_FAIL",
};
export default apiConstants;
