const apiConstants = {

    GET_USER: "GET_USER",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAIL: "GET_USER_FAIL",

    AUTH: "AUTH",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",

    GET_USER_WISHLIST: "GET_USER_WISHLIST",
    GET_USER_WISHLIST_SUCCESS: "GET_USER_WISHLIST_SUCCESS",
    GET_USER_WISHLIST_FAIL: "GET_USER_WISHLIST_FAIL",

    GET_USER_CART: "GET_USER_CART",
    GET_USER_CART_SUCCESS: "GET_USER_CART_SUCCESS",
    GET_USER_CART_FAIL: "GET_USER_CART_FAIL",

    MODIFIY_WISHLIST: "MODIFIY_WISHLIST",
    MODIFIY_WISHLIST_SUCCESS: "MODIFIY_WISHLIST_SUCCESS",
    MODIFIY_WISHLIST_FAIL: "MODIFIY_WISHLIST_FAIL",

};
export default apiConstants;
